### ISSUE TITLE
Maimy

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#14]
### Integrated into her pk3 (legacy BP changes)
- Parrying Maimy's mace causes her to tumble

### Current BP additions
- Fixed friendly teammates being able to parry her mace... lol....
- Mace hitbox increase (18 fracs -> 22 fracs)
- Less actioncost (12 -> 10)
- Maimy can no longer perform her jump ability during a shield ability
- Mace spin can now be instantly cancelled into guard or Mace attack
- (Thx Inazuma ❤) During Maimy’s double jump charge: Press battle special to do an instant dash mode. The initial thrust you get is dependent on how long you charge.
- Maimy no longer retains dashmode after a collision

**Comment by felixLumyni** [comment]
TODO: Buff

**Comment by Smol6606** [comment]
![Image](https://github.com/felixLumyni/battlepatch/assets/151889205/6c1aec8c-bde8-480a-a8b5-87141232a8e4)

![Image](https://github.com/felixLumyni/battlepatch/assets/151889205/7d8a1898-433c-4508-be4f-866ed538b543)

Possible New BM/Rework , Mace Throw!
Maimy Begins Mace Spinning, Holding the BM Button charges up the Windup Meter, once charged let go of the BM Button to release the mace for a throw! the maceball bounces around for damage, and disappears after a few bounces.
