### ISSUE TITLE
Github repo is incorrectly named battlepatch

### ISSUE THREAD

**Issue by electrolys** [felixLumyni/battlepass#24]
The GitHub repo hasn't changed names yet to reflect the only proper name for this mod that is BattlePass such should be resolved immediately

**Comment by felixLumyni** [comment]
I'm delighted to inform you that the issue regarding the GitHub repo name has been rectified promptly. The repo now proudly bears the rightful title of "BattlePass," aligning perfectly with its essence.

Thank you for bringing this to my attention.
