### ISSUE TITLE
L_WilloPatch

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#5]
*NOTE: This is not a "pass", it's still a "patch", meaning this does NOT include the character in this pk3, only the LUA code.*

[DOWNLOAD v7.2](https://cdn.discordapp.com/attachments/1313999538041917512/1329215442404900884/L_WilloPatch-v7.2.pk3?ex=678987d9&is=67883659&hm=10bad7fc1779d62fa0611312038677badfc6b34b138fb51795557c540ff1f028&)

- Weight: 95
- No longer has shield stocks
- Implemented exhaust function that slows most of his abilities when Willo is exhausted
- Spooky dance cannot be cancelled with guard, and the music is properly interrupted along with it

| Core Gimmick | Description |
| ------------- | ------------- |
| 🫧 Souls | - Another type of cost for his battle moves, indicated by a new HUD element <br> - Increases up to 3 when collecting a large item bubble, or four small item bubbles. |
| 🔥 Ethereal | - Flinches and drops flags when applied, damages if the player was already afflicted <br> - Intangible: Prevents collision with players, rings, flags and item bubbles <br> - For Willo, wears off after exiting his state. For opponents, wears off after a few seconds at most |

### Main ability changes:
- Halved upwards momentum obtained from jump ability, also halved speed if Willo is above runspeed
- Is 🔥 Ethereal, applies it to opponents on collision (3s)
- Cannot cancel into itself or into air dodge
- Is cancelled when in contact with item bubbles

# Battle specials:

| Battle special | Cost | Cooldown | What it does |
| ------------- | ------------- | ------------- | ------------- |
| 🦇 Shadow Totem | >3 souls | Zero | - Launches a 🦇 Shadow Totem (lasts for 18 seconds if no souls are spent or gained) that limits the opposing team's vision of the level and unlocks Willo's totem abilities <br> - Darkness is temporarily disabled when Willo takes damage, flinches or tumbles <br> - Dies if Willo dies <br> - Every time it touches the floor, creates a tumbling shockwave <br> - Spikes opponents and makes them 🔥 Ethereal when falling on top of them |
| 🌫 Phase Attack | 10 rings | 2 seconds | - Overrides ALL abilities if Willo is moving or spindashing <br> - 🔥 Ethereal dash that depends on Willo's speed <br> - On collision with an opponent, makes them 🔥 Ethereal for 3 seconds and extracts their shield, or up to 20 of their rings into item bubbles which slightly move towards him. Also steals 25 score if the affected player didn't take damage in the interaction. <br> - Holding spin when colliding with a wall causes Willo to curl into a spindash <br> - On collision with a 🦇 Shadow Totem, Willo curls into a jump and bashes it downwards when it is in the air, or upwards when it is on the floor <br> - Once per jump, allows Willo to use his jump ability once again <br> - Can be freely steered with the camera, and braked by releasing the special button <br> - While active, Willo has unlimited stamina |
| ‍💫 Recall Bash | 1 small soul | 1 second | - Requires an active 🦇 Shadow Totem <br> - Is an instant 🌫 Phase Attack that homes into the 🦇 Shadow Totem |
| ‍🌌 Dispell Pulse | 1 small soul | 1.5 seconds | - Requires an active 🦇 Shadow Totem <br> - Is a secondary ability (Performed by flag toss) <br> - The totem creates a powerful shockwave that briefly makes them 🔥 Ethereal for 3 seconds and cleanses ALL powerups from enemies, including custom buffs |
| 💥Detach Shield | 1 shield | Zero | - Is a secondary ability (Performed by flag toss) while 🦇 Shadow Totem is not active <br> - Toss the current shield to gain 1 soul (Except if it was a pink/pity shield) <br> - The shield won't be collectable by other Willos, indicated by a black bubble <br> - When activated, Willo's stamina is fully replenished |

**Comment by Smol6606** [comment]
My Suggestions to Willo
- pressing spin on the ground/air during Dark ascent charged shoots a moving ghost ember
- activating ghost form unlocks a dash battlemove that attacks through players (faze through)
- totem making the map dark (for enemy team/players), and if near a enemy, shoots fire

![Image](https://github.com/felixLumyni/battlepatch/assets/151889205/36d4b461-00e6-46cf-b0c7-812f8a316885)

**Comment by felixLumyni** [comment]
as of v4.2, i'd say he is successfully patched
